.git
.gitignore
.idea
.vscode
.codex
.agents
.trae
.pnpm-store

**/node_modules
**/.next
**/target
**/.cache
**/dist
**/unpackage
**/*.log
**/.env
**/.env.*

ai_service
backend
docs
frontend
scripts
storage
