CREATE TABLE IF NOT EXISTS herb_species (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    herb_code VARCHAR(64) NOT NULL COMMENT 'Unique herb code',
    herb_name VARCHAR(100) NOT NULL COMMENT 'Herb name',
    latin_name VARCHAR(255) NULL COMMENT 'Latin name',
    alias_name VARCHAR(255) NULL COMMENT 'Alias names',
    category VARCHAR(100) NULL COMMENT 'Herb category',
    medicinal_part VARCHAR(100) NULL COMMENT 'Medicinal part',
    efficacy TEXT NULL COMMENT 'Efficacy description',
    description TEXT NULL COMMENT 'Herb description',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_species_herb_code (herb_code),
    KEY idx_herb_species_herb_name (herb_name),
    KEY idx_herb_species_category (category),
    KEY idx_herb_species_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Herb species master data';

CREATE TABLE IF NOT EXISTS herb_ai_model_version (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    model_code VARCHAR(100) NOT NULL COMMENT 'Unique model code',
    model_name VARCHAR(100) NOT NULL COMMENT 'Model name',
    version VARCHAR(100) NULL COMMENT 'Model version',
    model_type VARCHAR(50) NULL COMMENT 'Model type',
    model_path VARCHAR(500) NULL COMMENT 'Model file path or service address',
    accuracy DECIMAL(8,4) NULL COMMENT 'Model accuracy',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
    description TEXT NULL COMMENT 'Model description',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_ai_model_version_model_code (model_code),
    KEY idx_herb_ai_model_version_model_type (model_type),
    KEY idx_herb_ai_model_version_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI recognition model version';

CREATE TABLE IF NOT EXISTS herb_atlas (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    species_id BIGINT NOT NULL COMMENT 'Herb species id',
    atlas_code VARCHAR(64) NOT NULL COMMENT 'Unique atlas code',
    image_url VARCHAR(500) NOT NULL COMMENT 'Standard atlas image URL',
    image_name VARCHAR(255) NULL COMMENT 'Image name',
    image_type VARCHAR(50) NULL COMMENT 'Image type',
    growth_stage VARCHAR(50) NULL COMMENT 'Growth stage',
    medicinal_part VARCHAR(100) NULL COMMENT 'Medicinal part',
    source VARCHAR(255) NULL COMMENT 'Atlas source',
    description TEXT NULL COMMENT 'Atlas description',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_atlas_atlas_code (atlas_code),
    KEY idx_herb_atlas_species_id (species_id),
    KEY idx_herb_atlas_image_type (image_type),
    KEY idx_herb_atlas_growth_stage (growth_stage),
    KEY idx_herb_atlas_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Standard herb atlas image';

CREATE TABLE IF NOT EXISTS herb_atlas_tag (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    atlas_id BIGINT NOT NULL COMMENT 'Standard atlas id',
    tag_name VARCHAR(100) NOT NULL COMMENT 'Tag name',
    tag_type VARCHAR(50) NULL COMMENT 'Tag type',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_atlas_tag_atlas_id (atlas_id),
    KEY idx_herb_atlas_tag_tag_name (tag_name),
    KEY idx_herb_atlas_tag_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Standard atlas tag';

CREATE TABLE IF NOT EXISTS herb_image (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    image_code VARCHAR(64) NOT NULL COMMENT 'Unique uploaded image code',
    species_id BIGINT NULL COMMENT 'Herb species id',
    image_url VARCHAR(500) NOT NULL COMMENT 'Uploaded image URL',
    image_name VARCHAR(255) NULL COMMENT 'Image name',
    upload_source VARCHAR(50) NULL COMMENT 'Upload source: pc, uni_app, app',
    collector_id BIGINT NULL COMMENT 'Collector user id',
    base_id BIGINT NULL COMMENT 'Herb base id',
    collect_place VARCHAR(255) NULL COMMENT 'Collect place',
    collect_time DATETIME NULL COMMENT 'Collect time',
    image_type VARCHAR(50) NULL COMMENT 'Image type',
    growth_stage VARCHAR(50) NULL COMMENT 'Growth stage',
    health_status VARCHAR(50) NULL COMMENT 'Health status',
    process_status VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'Process status',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_image_image_code (image_code),
    KEY idx_herb_image_species_id (species_id),
    KEY idx_herb_image_collector_id (collector_id),
    KEY idx_herb_image_base_id (base_id),
    KEY idx_herb_image_process_status (process_status),
    KEY idx_herb_image_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User uploaded herb image';

CREATE TABLE IF NOT EXISTS herb_image_recognition (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    image_id BIGINT NOT NULL COMMENT 'Uploaded image id',
    model_version_id BIGINT NULL COMMENT 'AI model version id',
    predicted_species_id BIGINT NULL COMMENT 'Predicted herb species id',
    predicted_name VARCHAR(100) NULL COMMENT 'Predicted herb name',
    confidence DECIMAL(8,6) NULL COMMENT 'Recognition confidence',
    recognition_status VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'Recognition status',
    recognition_time DATETIME NULL COMMENT 'Recognition time',
    raw_result TEXT NULL COMMENT 'Raw recognition result',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_image_recognition_image_id (image_id),
    KEY idx_herb_image_recognition_model_version_id (model_version_id),
    KEY idx_herb_image_recognition_predicted_species_id (predicted_species_id),
    KEY idx_herb_image_recognition_status (recognition_status),
    KEY idx_herb_image_recognition_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Herb image recognition result';

CREATE TABLE IF NOT EXISTS herb_image_match (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    image_id BIGINT NOT NULL COMMENT 'Uploaded image id',
    atlas_id BIGINT NOT NULL COMMENT 'Matched standard atlas id',
    similarity_score DECIMAL(8,6) NULL COMMENT 'Similarity score',
    match_rank INT NULL COMMENT 'Match rank',
    match_result VARCHAR(50) NULL COMMENT 'Match result',
    match_batch_no VARCHAR(100) NULL COMMENT 'Match batch number',
    match_time DATETIME NULL COMMENT 'Match time',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_image_match_image_id (image_id),
    KEY idx_herb_image_match_batch (image_id, match_batch_no),
    KEY idx_herb_image_match_atlas_id (atlas_id),
    KEY idx_herb_image_match_rank (match_rank),
    KEY idx_herb_image_match_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Uploaded image and standard atlas match record';

CREATE TABLE IF NOT EXISTS herb_identification_result (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    image_id BIGINT NOT NULL COMMENT 'Uploaded image id',
    best_match_id BIGINT NULL COMMENT 'Best local atlas match id',
    recognition_id BIGINT NULL COMMENT 'Auxiliary recognition record id',
    final_species_id BIGINT NULL COMMENT 'Final identified herb species id',
    final_species_name VARCHAR(100) NULL COMMENT 'Final identified herb species name',
    final_confidence DECIMAL(10,4) NULL COMMENT 'Final confidence or similarity',
    result_source VARCHAR(50) NULL COMMENT 'Result source: local_match, doubao_review, manual_review',
    match_result VARCHAR(50) NULL COMMENT 'Local match result',
    need_review TINYINT NOT NULL DEFAULT 0 COMMENT 'Need manual review: 0 no, 1 yes',
    review_status VARCHAR(50) NULL COMMENT 'Review status: pending, confirmed, rejected',
    suggestion VARCHAR(500) NULL COMMENT 'System suggestion',
    review_comment VARCHAR(500) NULL COMMENT 'Manual review comment',
    reviewer_id BIGINT NULL COMMENT 'Reviewer user id',
    reviewer_name VARCHAR(100) NULL COMMENT 'Reviewer name',
    review_time DATETIME NULL COMMENT 'Review time',
    raw_summary LONGTEXT NULL COMMENT 'Identification flow summary JSON',
    identify_time DATETIME NULL COMMENT 'Identify time',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_identification_image_id (image_id),
    KEY idx_herb_identification_species_id (final_species_id),
    KEY idx_herb_identification_source (result_source),
    KEY idx_herb_identification_match_result (match_result),
    KEY idx_herb_identification_review (need_review, review_status),
    KEY idx_herb_identification_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Final herb image identification result';

CREATE TABLE IF NOT EXISTS herb_atlas_feature (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    atlas_id BIGINT NOT NULL COMMENT 'Standard atlas id',
    species_id BIGINT NULL COMMENT 'Herb species id',
    feature_code VARCHAR(100) NULL COMMENT 'Feature code',
    feature_vector LONGTEXT NOT NULL COMMENT 'Feature vector JSON',
    feature_dimension INT NULL COMMENT 'Feature vector dimension',
    feature_model VARCHAR(100) NULL COMMENT 'Feature extraction model name',
    feature_version VARCHAR(50) NULL COMMENT 'Feature extraction model version',
    extract_status VARCHAR(30) NOT NULL COMMENT 'Extract status',
    extract_time DATETIME NULL COMMENT 'Extract time',
    error_message VARCHAR(500) NULL COMMENT 'Failure reason',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_atlas_feature_atlas_id (atlas_id),
    KEY idx_herb_atlas_feature_species_id (species_id),
    KEY idx_herb_atlas_feature_model (feature_model, feature_version),
    KEY idx_herb_atlas_feature_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Standard atlas feature vector';

CREATE TABLE IF NOT EXISTS herb_image_feature (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    image_id BIGINT NOT NULL COMMENT 'Uploaded image id',
    species_id BIGINT NULL COMMENT 'Herb species id',
    feature_code VARCHAR(100) NULL COMMENT 'Feature code',
    feature_vector LONGTEXT NOT NULL COMMENT 'Feature vector JSON',
    feature_dimension INT NULL COMMENT 'Feature vector dimension',
    feature_model VARCHAR(100) NULL COMMENT 'Feature extraction model name',
    feature_version VARCHAR(50) NULL COMMENT 'Feature extraction model version',
    extract_status VARCHAR(30) NOT NULL COMMENT 'Extract status',
    extract_time DATETIME NULL COMMENT 'Extract time',
    error_message VARCHAR(500) NULL COMMENT 'Failure reason',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_herb_image_feature_image_id (image_id),
    KEY idx_herb_image_feature_species_id (species_id),
    KEY idx_herb_image_feature_model (feature_model, feature_version),
    KEY idx_herb_image_feature_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Uploaded image feature vector';

CREATE TABLE IF NOT EXISTS herb_knowledge_entity (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    entity_code VARCHAR(100) NOT NULL COMMENT 'Unique entity code',
    entity_name VARCHAR(255) NOT NULL COMMENT 'Entity name',
    entity_type VARCHAR(100) NOT NULL COMMENT 'Entity type',
    related_id BIGINT NULL COMMENT 'Related business id',
    description TEXT NULL COMMENT 'Entity description',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_knowledge_entity_entity_code (entity_code),
    KEY idx_herb_knowledge_entity_type (entity_type),
    KEY idx_herb_knowledge_entity_related_id (related_id),
    KEY idx_herb_knowledge_entity_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Knowledge graph entity';

CREATE TABLE IF NOT EXISTS herb_knowledge_relation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    relation_code VARCHAR(100) NOT NULL COMMENT 'Unique relation code',
    relation_name VARCHAR(100) NOT NULL COMMENT 'Relation name',
    relation_type VARCHAR(100) NULL COMMENT 'Relation type',
    description TEXT NULL COMMENT 'Relation description',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_knowledge_relation_code (relation_code),
    KEY idx_herb_knowledge_relation_type (relation_type),
    KEY idx_herb_knowledge_relation_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Knowledge graph relation type';

CREATE TABLE IF NOT EXISTS herb_knowledge_triple (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    subject_entity_id BIGINT NOT NULL COMMENT 'Subject entity id',
    relation_id BIGINT NOT NULL COMMENT 'Relation id',
    object_entity_id BIGINT NOT NULL COMMENT 'Object entity id',
    confidence DECIMAL(8,6) NULL COMMENT 'Triple confidence',
    source VARCHAR(255) NULL COMMENT 'Triple source',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_herb_knowledge_triple_sro (subject_entity_id, relation_id, object_entity_id),
    KEY idx_herb_knowledge_triple_subject (subject_entity_id),
    KEY idx_herb_knowledge_triple_relation (relation_id),
    KEY idx_herb_knowledge_triple_object (object_entity_id),
    KEY idx_herb_knowledge_triple_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Knowledge graph triple';
