-- PR #4 adds recognition feature data and the collection batch workflow.
-- Existing herb master, atlas, image, recognition and match tables are created by V20260708_001.

CREATE TABLE `herb_atlas_feature` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `atlas_id` BIGINT NOT NULL COMMENT '标准图谱 ID',
  `species_id` BIGINT NULL DEFAULT NULL COMMENT '药材品种 ID',
  `feature_code` VARCHAR(100) NULL DEFAULT NULL COMMENT '特征编码',
  `feature_vector` LONGTEXT NOT NULL COMMENT '特征向量 JSON',
  `feature_dimension` INT NULL DEFAULT NULL COMMENT '特征向量维度',
  `feature_model` VARCHAR(100) NULL DEFAULT NULL COMMENT '特征提取模型名称',
  `feature_version` VARCHAR(50) NULL DEFAULT NULL COMMENT '特征提取模型版本',
  `extract_status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT '提取状态：pending、success、failed',
  `extract_time` DATETIME NULL DEFAULT NULL COMMENT '特征提取时间',
  `error_message` VARCHAR(500) NULL DEFAULT NULL COMMENT '失败原因',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_herb_atlas_feature_atlas_id` (`atlas_id`),
  KEY `idx_herb_atlas_feature_species_id` (`species_id`),
  KEY `idx_herb_atlas_feature_model` (`feature_model`, `feature_version`),
  KEY `idx_herb_atlas_feature_status` (`extract_status`, `is_deleted`)
) ENGINE=InnoDB COMMENT='标准图谱特征向量表；保存图谱图片的可检索特征。';

CREATE TABLE `herb_image_feature` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `image_id` BIGINT NOT NULL COMMENT '用户图片 ID',
  `species_id` BIGINT NULL DEFAULT NULL COMMENT '药材品种 ID',
  `feature_code` VARCHAR(100) NULL DEFAULT NULL COMMENT '特征编码',
  `feature_vector` LONGTEXT NOT NULL COMMENT '特征向量 JSON',
  `feature_dimension` INT NULL DEFAULT NULL COMMENT '特征向量维度',
  `feature_model` VARCHAR(100) NULL DEFAULT NULL COMMENT '特征提取模型名称',
  `feature_version` VARCHAR(50) NULL DEFAULT NULL COMMENT '特征提取模型版本',
  `extract_status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT '提取状态：pending、success、failed',
  `extract_time` DATETIME NULL DEFAULT NULL COMMENT '特征提取时间',
  `error_message` VARCHAR(500) NULL DEFAULT NULL COMMENT '失败原因',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_herb_image_feature_image_id` (`image_id`),
  KEY `idx_herb_image_feature_species_id` (`species_id`),
  KEY `idx_herb_image_feature_model` (`feature_model`, `feature_version`),
  KEY `idx_herb_image_feature_status` (`extract_status`, `is_deleted`)
) ENGINE=InnoDB COMMENT='用户图片特征向量表；保存上传图片的可检索特征。';

CREATE TABLE `herb_identification_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `image_id` BIGINT NOT NULL COMMENT '用户图片 ID',
  `best_match_id` BIGINT NULL DEFAULT NULL COMMENT '最佳本地图谱匹配记录 ID',
  `recognition_id` BIGINT NULL DEFAULT NULL COMMENT '辅助 AI 识别记录 ID',
  `final_species_id` BIGINT NULL DEFAULT NULL COMMENT '最终识别药材 ID',
  `final_species_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '最终识别药材名称',
  `final_confidence` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '最终置信度或相似度',
  `result_source` VARCHAR(50) NULL DEFAULT NULL COMMENT '结果来源：local_match、doubao_review、manual_review',
  `match_result` VARCHAR(50) NULL DEFAULT NULL COMMENT '匹配结果',
  `need_review` TINYINT NOT NULL DEFAULT 0 COMMENT '是否需要人工复核',
  `review_status` VARCHAR(50) NULL DEFAULT NULL COMMENT '复核状态：pending、confirmed、rejected',
  `suggestion` VARCHAR(500) NULL DEFAULT NULL COMMENT '系统建议',
  `review_comment` VARCHAR(500) NULL DEFAULT NULL COMMENT '人工复核意见',
  `reviewer_id` BIGINT NULL DEFAULT NULL COMMENT '复核人用户 ID',
  `reviewer_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '复核人姓名快照',
  `review_time` DATETIME NULL DEFAULT NULL COMMENT '复核时间',
  `raw_summary` LONGTEXT NULL COMMENT '识别流程摘要 JSON',
  `identify_time` DATETIME NULL DEFAULT NULL COMMENT '识别完成时间',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_herb_identification_result_image_id` (`image_id`),
  KEY `idx_herb_identification_result_species_id` (`final_species_id`),
  KEY `idx_herb_identification_result_source` (`result_source`),
  KEY `idx_herb_identification_result_match` (`match_result`),
  KEY `idx_herb_identification_result_review` (`need_review`, `review_status`)
) ENGINE=InnoDB COMMENT='中药材图片最终识别结果表；保存本地图谱、辅助 AI 和人工复核结论。';

CREATE TABLE `herb_collection_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `task_code` VARCHAR(64) NOT NULL COMMENT '采集任务编码',
  `task_name` VARCHAR(255) NOT NULL COMMENT '采集任务名称',
  `species_id` BIGINT NULL DEFAULT NULL COMMENT '目标药材品种 ID',
  `species_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '目标药材名称快照',
  `base_id` BIGINT NULL DEFAULT NULL COMMENT '种植基地 ID',
  `base_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '基地名称快照',
  `collect_place` VARCHAR(255) NULL DEFAULT NULL COMMENT '采集地点',
  `planned_start_time` DATETIME NULL DEFAULT NULL COMMENT '计划开始时间',
  `planned_end_time` DATETIME NULL DEFAULT NULL COMMENT '计划结束时间',
  `collector_id` BIGINT NULL DEFAULT NULL COMMENT '采集人用户 ID',
  `collector_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '采集人姓名快照',
  `task_status` VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT '任务状态：draft、published、in_progress、completed、cancelled',
  `description` TEXT NULL COMMENT '任务说明',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_herb_collection_task_task_code` (`task_code`),
  KEY `idx_herb_collection_task_species_id` (`species_id`),
  KEY `idx_herb_collection_task_collector_id` (`collector_id`),
  KEY `idx_herb_collection_task_status` (`task_status`),
  KEY `idx_herb_collection_task_planned_time` (`planned_start_time`, `planned_end_time`)
) ENGINE=InnoDB COMMENT='中药材采集任务表；保存采集人员、目标药材和计划时间。';

CREATE TABLE `herb_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `batch_code` VARCHAR(64) NOT NULL COMMENT '批次编码',
  `batch_name` VARCHAR(255) NOT NULL COMMENT '批次名称',
  `task_id` BIGINT NULL DEFAULT NULL COMMENT '采集任务 ID',
  `species_id` BIGINT NULL DEFAULT NULL COMMENT '药材品种 ID',
  `species_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '药材名称快照',
  `base_id` BIGINT NULL DEFAULT NULL COMMENT '种植基地 ID',
  `base_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '基地名称快照',
  `origin_place` VARCHAR(255) NULL DEFAULT NULL COMMENT '产地或采集地点',
  `collect_start_time` DATETIME NULL DEFAULT NULL COMMENT '批次采集开始时间',
  `collect_end_time` DATETIME NULL DEFAULT NULL COMMENT '批次采集结束时间',
  `harvest_time` DATETIME NULL DEFAULT NULL COMMENT '采收时间',
  `production_date` DATE NULL DEFAULT NULL COMMENT '生产日期',
  `batch_status` VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT '批次状态',
  `image_count` INT NOT NULL DEFAULT 0 COMMENT '绑定图片数量',
  `identified_count` INT NOT NULL DEFAULT 0 COMMENT '已有识别结果的图片数量',
  `reviewed_count` INT NOT NULL DEFAULT 0 COMMENT '已人工复核图片数量',
  `need_review_count` INT NOT NULL DEFAULT 0 COMMENT '需要人工复核图片数量',
  `final_species_id` BIGINT NULL DEFAULT NULL COMMENT '最终确认药材 ID',
  `final_species_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '最终确认药材名称',
  `avg_similarity` DECIMAL(10,6) NULL DEFAULT NULL COMMENT '平均相似度',
  `quality_level` VARCHAR(50) NULL DEFAULT NULL COMMENT '质量等级',
  `quality_score` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '质量评分',
  `evaluation_summary` TEXT NULL COMMENT '批次评价摘要',
  `trace_code` VARCHAR(100) NULL DEFAULT NULL COMMENT '追溯编码',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_herb_batch_batch_code` (`batch_code`),
  KEY `idx_herb_batch_task_id` (`task_id`),
  KEY `idx_herb_batch_species_id` (`species_id`),
  KEY `idx_herb_batch_status` (`batch_status`),
  KEY `idx_herb_batch_trace_code` (`trace_code`),
  KEY `idx_herb_batch_collect_time` (`collect_start_time`, `collect_end_time`)
) ENGINE=InnoDB COMMENT='中药材批次档案表；保存采集批次、识别汇总和质量评价。';

CREATE TABLE `herb_batch_image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `batch_id` BIGINT NOT NULL COMMENT '批次 ID',
  `image_id` BIGINT NOT NULL COMMENT '采集图片 ID',
  `identification_result_id` BIGINT NULL DEFAULT NULL COMMENT '最终识别结果 ID',
  `image_role` VARCHAR(50) NULL DEFAULT NULL COMMENT '图片角色：leaf、root、flower、whole_plant、medicinal_part、other',
  `is_primary` TINYINT NOT NULL DEFAULT 0 COMMENT '是否主图',
  `bind_status` VARCHAR(50) NOT NULL DEFAULT 'bound' COMMENT '绑定状态：bound、removed',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  `deleted_by` BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_herb_batch_image_batch_id` (`batch_id`),
  KEY `idx_herb_batch_image_image_id` (`image_id`),
  KEY `idx_herb_batch_image_result_id` (`identification_result_id`),
  KEY `idx_herb_batch_image_binding` (`batch_id`, `image_id`, `is_deleted`)
) ENGINE=InnoDB COMMENT='中药材批次图片关联表；保存批次与采集图片的绑定关系。';
