CREATE TABLE herb_trace_hash_archive (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  task_id BIGINT NOT NULL COMMENT '采集任务 ID',
  hash_version INT NOT NULL COMMENT '证据链版本',
  root_hash CHAR(64) NOT NULL COMMENT '档案根哈希',
  event_count INT NOT NULL COMMENT '关键事件数量',
  generated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
  generated_by BIGINT NULL DEFAULT NULL COMMENT '生成人 ID',
  integrity_status VARCHAR(20) NOT NULL DEFAULT 'generated' COMMENT '完整性状态',
  remark VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  updated_by BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  deleted_at DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  deleted_by BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_trace_hash_archive_version (task_id, hash_version),
  KEY idx_trace_hash_archive_task_time (task_id, generated_time)
) ENGINE=InnoDB COMMENT='数字生命档案哈希证据链版本';

CREATE TABLE herb_trace_hash_event (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  task_id BIGINT NOT NULL COMMENT '采集任务 ID',
  hash_version INT NOT NULL COMMENT '证据链版本',
  target_type VARCHAR(40) NOT NULL COMMENT '业务对象类型',
  target_id BIGINT NOT NULL COMMENT '业务对象 ID',
  event_type VARCHAR(50) NOT NULL COMMENT '事件类型',
  event_time DATETIME NOT NULL COMMENT '真实业务事件时间',
  actor_id BIGINT NULL DEFAULT NULL COMMENT '操作人 ID',
  actor_name VARCHAR(100) NULL DEFAULT NULL COMMENT '操作人姓名快照',
  payload_snapshot TEXT NOT NULL COMMENT '规范化事件 JSON',
  previous_hash CHAR(64) NULL DEFAULT NULL COMMENT '上一事件哈希',
  event_hash CHAR(64) NOT NULL COMMENT '当前事件哈希',
  sequence INT NOT NULL COMMENT '链内连续序号',
  remark VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  updated_by BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  deleted_at DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  deleted_by BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_trace_hash_event_sequence (task_id, hash_version, sequence),
  KEY idx_trace_hash_event_task_version (task_id, hash_version)
) ENGINE=InnoDB COMMENT='数字生命档案哈希证据链事件';
