CREATE TABLE herb_digital_life_narration (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  task_id BIGINT NOT NULL COMMENT '采集任务 ID',
  batch_id BIGINT NOT NULL COMMENT '采集批次 ID',
  growth_record_id BIGINT NOT NULL COMMENT '生长记录 ID',
  narration_type VARCHAR(30) NOT NULL COMMENT '解说类型：stage_summary、archive_summary',
  narration_text VARCHAR(1000) NOT NULL COMMENT '缓存解说正文',
  narration_source VARCHAR(20) NOT NULL COMMENT '解说来源：ai、template',
  input_snapshot CHAR(64) NOT NULL COMMENT '规范化输入 SHA-256 快照',
  prompt_version VARCHAR(30) NOT NULL COMMENT '提示词版本',
  model_name VARCHAR(100) NULL DEFAULT NULL COMMENT '生成模型名称',
  generated_by BIGINT NULL DEFAULT NULL COMMENT '生成人 ID',
  generated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
  remark VARCHAR(500) NULL DEFAULT NULL COMMENT '备注',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
  updated_by BIGINT NULL DEFAULT NULL COMMENT '更新人 ID',
  deleted_at DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  deleted_by BIGINT NULL DEFAULT NULL COMMENT '删除人 ID',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_digital_life_narration_version (growth_record_id, narration_type, prompt_version),
  KEY idx_digital_life_narration_task (task_id),
  KEY idx_digital_life_narration_batch (batch_id)
) ENGINE=InnoDB COMMENT='数字生命档案阶段解说缓存';
