CREATE TABLE IF NOT EXISTS herb_collection_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    task_code VARCHAR(64) NOT NULL COMMENT 'Collection task code, for example TASK_20260710_001',
    task_name VARCHAR(255) NOT NULL COMMENT 'Collection task name',
    species_id BIGINT NULL COMMENT 'Target herb species id',
    species_name VARCHAR(100) NULL COMMENT 'Target herb species name snapshot',
    base_id BIGINT NULL COMMENT 'Planting base id, reserved',
    base_name VARCHAR(255) NULL COMMENT 'Planting base name snapshot',
    collect_place VARCHAR(255) NULL COMMENT 'Collection place',
    planned_start_time DATETIME NULL COMMENT 'Planned collection start time',
    planned_end_time DATETIME NULL COMMENT 'Planned collection end time',
    collector_id BIGINT NULL COMMENT 'Collector user id, reserved',
    collector_name VARCHAR(100) NULL COMMENT 'Collector name snapshot',
    task_status VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT 'Task status: draft, published, in_progress, completed, cancelled',
    description TEXT NULL COMMENT 'Task description',
    remark VARCHAR(500) NULL COMMENT 'Remark',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY idx_task_code (task_code),
    KEY idx_species_id (species_id),
    KEY idx_collector_id (collector_id),
    KEY idx_task_status (task_status),
    KEY idx_planned_time (planned_start_time, planned_end_time),
    KEY idx_herb_collection_task_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Herb collection task';

CREATE TABLE IF NOT EXISTS herb_batch (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    batch_code VARCHAR(64) NOT NULL COMMENT 'Batch code, for example BATCH_20260710_001',
    batch_name VARCHAR(255) NOT NULL COMMENT 'Batch name',
    task_id BIGINT NULL COMMENT 'Related collection task id',
    species_id BIGINT NULL COMMENT 'Herb species id',
    species_name VARCHAR(100) NULL COMMENT 'Herb species name snapshot',
    base_id BIGINT NULL COMMENT 'Planting base id, reserved',
    base_name VARCHAR(255) NULL COMMENT 'Planting base name snapshot',
    origin_place VARCHAR(255) NULL COMMENT 'Origin or collection place',
    collect_start_time DATETIME NULL COMMENT 'Batch collection start time',
    collect_end_time DATETIME NULL COMMENT 'Batch collection end time',
    harvest_time DATETIME NULL COMMENT 'Harvest time',
    production_date DATE NULL COMMENT 'Production date',
    batch_status VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT 'Batch status: draft, collecting, submitted, identifying, reviewing, confirmed, archived, cancelled',
    image_count INT NOT NULL DEFAULT 0 COMMENT 'Bound image count',
    identified_count INT NOT NULL DEFAULT 0 COMMENT 'Image count with identification result',
    reviewed_count INT NOT NULL DEFAULT 0 COMMENT 'Manually reviewed image count',
    need_review_count INT NOT NULL DEFAULT 0 COMMENT 'Image count requiring manual review',
    final_species_id BIGINT NULL COMMENT 'Final confirmed herb species id',
    final_species_name VARCHAR(100) NULL COMMENT 'Final confirmed herb species name',
    avg_similarity DECIMAL(10,6) NULL COMMENT 'Average similarity score',
    quality_level VARCHAR(50) NULL COMMENT 'Batch quality level: excellent, good, normal, poor',
    quality_score DECIMAL(10,4) NULL COMMENT 'Batch quality score',
    evaluation_summary TEXT NULL COMMENT 'Batch evaluation summary',
    trace_code VARCHAR(100) NULL COMMENT 'Trace code reserved for QR traceability',
    remark VARCHAR(500) NULL COMMENT 'Remark',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    UNIQUE KEY idx_batch_code (batch_code),
    KEY idx_task_id (task_id),
    KEY idx_species_id (species_id),
    KEY idx_batch_status (batch_status),
    KEY idx_trace_code (trace_code),
    KEY idx_collect_time (collect_start_time, collect_end_time),
    KEY idx_herb_batch_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Herb batch archive';

CREATE TABLE IF NOT EXISTS herb_batch_image (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    batch_id BIGINT NOT NULL COMMENT 'Batch id',
    image_id BIGINT NOT NULL COMMENT 'Collected herb image id',
    identification_result_id BIGINT NULL COMMENT 'Final identification result id',
    image_role VARCHAR(50) NULL COMMENT 'Image role: leaf, root, flower, whole_plant, medicinal_part, other',
    is_primary TINYINT NOT NULL DEFAULT 0 COMMENT 'Primary image flag: 1 yes, 0 no',
    bind_status VARCHAR(50) NOT NULL DEFAULT 'bound' COMMENT 'Bind status: bound, removed',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
    remark VARCHAR(500) NULL COMMENT 'Remark',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    PRIMARY KEY (id),
    KEY idx_batch_id (batch_id),
    KEY idx_image_id (image_id),
    KEY idx_identification_result_id (identification_result_id),
    UNIQUE KEY idx_batch_image_unique (batch_id, image_id, deleted),
    KEY idx_herb_batch_image_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Herb batch image relation';
